### ISSUE TITLE
Installing the beta version

### ISSUE THREAD

**Issue by cebthedev** [Saishy/certainmangareader#1]
Help, I don't know how to install your addon manually in my firefox, I have downloaded the source code but I dont know what steps I have to follow :( Can you help me plz. I want to install this version 2.0.0beta2.

**Comment by Saishy** [comment]
You may simply go to
https://addons.mozilla.org/en-US/firefox/addon/a-certain-manga-reader/versions/
and hover the beta2 version and click [+ Add to Firefox]

Cheers ^^

**Comment by cebthedev** [comment]
Thanks man :) I really enjoy using you add-on
