### ISSUE TITLE
Segfault on firefox 45.0.2

### ISSUE THREAD

**Issue by Keats** [Saishy/certainmangareader#10]
Trying to update the manga lists results in:

```
Vector smash protection is enabled.
[1]    29661 segmentation fault (core dumped)  firefox
[NPAPI 30007] ###!!! ABORT: Aborting on channel error.: file /build/firefox/src/firefox-45.0.2/ipc/glue/MessageChannel.cpp, line 1861
```

on Archlinux

**Comment by Keats** [comment]
@Saishy can you reproduce this?

**Comment by Saishy** [comment]
sorry for the delay, can you give me your manga list? you can export them if you update to beta.

**Comment by Keats** [comment]
Here's the export https://gist.github.com/Keats/cced29bf180b7631cdef2a8cecbe86f3

**Comment by Keats** [comment]
Updated to firefox 46 and the problem persists, let me know if i can help

**Comment by Keats** [comment]
@Saishy any update?

**Comment by Saishy** [comment]
Sorry, it's really hard to get a time for debugging, especially a side project :c

**Comment by Keats** [comment]
So i've emptied the list quite a bit, it seems the updater doesn't handle errors, ie if the manga is deleted on batoto, it will get stuck at that one. I guess the segfault was due to the same kind of issue

**Comment by Saishy** [comment]
I'm tackling the issue now, sorry for the delay.

**Comment by Keats** [comment]
Here's the cleaned down list https://gist.github.com/Keats/6829a009b6be682967213437213d564a

**Comment by Saishy** [comment]
A quick question, has you tried to log-in into bato.to before updating?

I think the culprit might be Ballroom e Youkoso, it's not possible to have access to the first chapter if you are not logged in. But I see no reason for it to give a segfault, and actually while updating your own list in my computer it doesn't give a segfault, only stops updating.

**Comment by Keats** [comment]
I just signed in and it managed to get further in the update but now segfaults again, the last it was able to update is Fairy Tail from that list

**Comment by Saishy** [comment]
Edit: Could you check if Dungeon Meshi is the problem?

**Comment by Keats** [comment]
Nope, removed it and it still crashes

**Comment by Keats** [comment]
Can you a debug option that gives a notification before updating a manga and space them by a few seconds? 
It would makes finding the culprit very fast, it's something after the letter B since those can update ok

**Comment by Saishy** [comment]
[segfault_cmr.txt](https://github.com/Saishy/certainmangareader/files/309752/segfault_cmr.txt)

I could get the error with this config, but it wasn't giving the error at all runs.

**Comment by Keats** [comment]
It seems to happen to random mangas actually. Do you have any idea why it happens?

**Comment by Saishy** [comment]
I have absolutely no idea, debugging it has been a pain since firefox doesn't have support for break on error.

Still working on it.

**Comment by Keats** [comment]
I might have a try at porting the extension to webextensions, those seem easier to maintain
