### ISSUE TITLE
Mangafox servers issue

### ISSUE THREAD

**Issue by Lery** [Saishy/certainmangareader#13]
It looks like there are new mangafox servers which should be added to image loading or that there are some problem, but most chapter are loading only the first 2-3 pages and then are not loading anymore.

I don't know how to diagnose the problem any further.

Also it seems like kissmanga isn't supported anymore.
On the other hand Batoto seems to be working fine, so I guess it isn't an issue with just my setup. 

But maybe it's Mangafox's fault, because they are giving a lot of 500 error and other problems when you read it one page at a time, so I guess it may just be that the extension is only trying once and when confronted to an internal server error it get stuck waiting for the image, maybe ?

**Comment by Saishy** [comment]
The extension should try once for each image server, tho mangafox has been
changing a lot of things internally and been a huge mess since last week :2
