### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by InstallGentoo11** [Saishy/certainmangareader#16]
It doesn't work on pages and I can't even click the icon on the toolbar. Though this is on pcxFirefox (I tested it and it works on a normal Firefox), so I am not sure if you would care.

Also changing the chapter from the addons UI doesn't work to begin with, it redirects back to the same chapter.

**Comment by Saishy** [comment]
Uh... I don't even know what is a pcxFirefox .-.
