### ISSUE TITLE
Slowdown in firefox with shaky connection

### ISSUE THREAD

**Issue by gagbo** [Saishy/certainmangareader#19]
Hi,

I've been using the plugin just for a few weeks, but I just discovered today (the hard way) that when the connection is shaky (a bad educational wi-fi network where every other site won't load because of timeouts), the plugin really **really** slows Firefox down. The unresponsiveness makes the whole application near not usable.

Firefox behaved normally again when I deactivated the plugin so I think it comes from here. The main difference when I activated vs. when I deactivated the plugin was the messages I got when I close Firefox (launched in terminal) :  
```
console.error: certainmanga: 
  Message: Error: Couldn't find the worker to receive this message. The script may not be initialized yet, or may already have been unloaded.
  Stack:
    processMessage@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/deprecated/sync-worker.js:241:11
emitEventToContent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/deprecated/sync-worker.js:287:3
UpdateNextManga@resource://gre/modules/commonjs/toolkit/loader.js -> resource://certainmangareader-at-saishy/lib/main.js:801:3
notify@resource://gre/modules/commonjs/sdk/timers.js:40:9
```
I had ~50/100 copies of this block following each other when I closed Firefox (55.0.1 (64 bits)) and the module was on.

**Comment by Saishy** [comment]
Hi,

Woa, sorry for that experience :c
The plugin is being reworked into webext, I will check that then.

**Comment by Saishy** [comment]
Closed issue as plugin is currently being ported to webext.
