### ISSUE TITLE
No longer working with batoto.

### ISSUE THREAD

**Issue by ghost** [Saishy/certainmangareader#4]
You're probably already aware, but bato.to is changing their reader.
I thought it might be nice to have that as a open issue here for now.
At the moment it is still possible to use it with the manga already on your reading list, but that should also break once they completely remove their old urls in a day or so.
Do you have any sort of estimate of when you might fix this?
Thanks.

Peter.

**Comment by Saishy** [comment]
Sadly yeah, I'm aware...

I was looking if they are going to maintain the direct link chapter list or if you will have to be logged at all.

**Comment by ghost** [comment]
Just checked, and it seems like they will remove any security they find out is unnecessary, so I guess it would be best to leave the issue for a few days.
Then again, I don't know the first thing about coding.
Best of luck!

**Comment by Saishy** [comment]
Hi there, sorry for the delay.

The 2.1.0 stable version is working with batoto, plus some more fixes and quality of life improvements ^^

**Comment by ghost** [comment]
Great, good job! While I'm here though, compact mode looks strange on my older macbook. 800p screen, picture attached. Thanks again!

![Compact](https://cloud.githubusercontent.com/assets/15304241/11766364/e96f02a2-a183-11e5-9d16-b7e520d29510.png)

**Comment by Saishy** [comment]
Oh, that was a bug that occurred when going to 2.0.0 and I totally forgot to fix it.
Since it's not a breaking bug I will fix it next year, mozilla seems to be taking too much time to review addons now.

Sorry for the 2.1.0 delay, nothing I can do but wait :c

**Comment by ghost** [comment]
No hurry with that. I already installed 2.1.0 as a unchecked beta from mozilla.
