### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by ghost** [Saishy/certainmangareader#5]
Hi again! The last update perfectly fixed the reader, but brought another problem. I am no longer getting any update notifications. The chapter lists themselves seem to update(don't take my word for it though) but the entries are not turning red or notifying. I'm still on a old 800p macbook if that's useful. Pictures attached - manga that I have not finished at all are red, but updates are not.
I only use batoto, so the other reader might work fine.

Might be that the ones like the first screenshot only show that there is a new chapter because I recently opened a previous one.

![Update](https://cloud.githubusercontent.com/assets/15304241/11852802/5bef4f68-a43a-11e5-8854-e15ab23d669e.png)
![Unread](https://cloud.githubusercontent.com/assets/15304241/11852801/5beed498-a43a-11e5-9f80-d81cc15e8007.png)

**Comment by Saishy** [comment]
I'm getting ready to travel and will be unable to work at the extension until late January :c

But I intend to implement an import/export feature so then you can pass me your list so I can test it. 

Tip: clicking at the addon logo near the title at the top will force update your list.

**Comment by ghost** [comment]
Thanks for the quick answer. Testing a bit more, the plugin does not check batoto by itself at all. It looks like the first screenshot when I check the last chapter I read of something I know updated.
Clicking the logo next to the title does not seem to do anything for me.

I can also test on my windows computer if you want. I'll be using an alternative plugin until the fix, looking forward to it.

EDIT: Forgot to mention, "Last updated" always says 0 on os x, but not on windows. Seems to be mac-only problem, I'll get the manga list over to my stationary to see if it updates. No reaction from the logo there either though

EDIT 2: It works fine on windows.

**Comment by ghost** [comment]
~~UPDATE: It seems to work fine now that I updated to Os X El Capitan.~~

~~UPDATE UPDATE: It only updates when it is reinstalled on El Capitan, I can't test on Yosemite anymore unfortunately. Pressing the icon does not force an update. On El Capitan the "Last updated" counter is accurate.~~

~~UPDATE UPDATE UPDATE: It updates by itself occasionally. It does seem to skip some updates, but I guess the computer might have been sleeping through them. It would be very nice if you could get a update button working.~~

LAST UPDATE: It is only broken on Yosemite, El Capitan is fine.
