### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by rjbs91** [Saishy/certainmangareader#6]
Hi. Love the add-on, but there's stuff I would like for you to add if possible:
- A permanent counter for how many series with new chapters are in the list (like AllMangasReader had)
- A button next to the blue arrow button to go to the next chapter
- A way to sync with a MyAnimeList account
- Mangacow support

**Comment by ghost** [comment]
Hijacking this post with some more requests if you don't mind. Saishy has not responded because they are away until "late January".

~~Any kind of sync between computers.~~ The exporting feature you mentioned.
Kissmanga and Crunchyroll support.
Sorting options.
Some sort of way to see or mark the difference between unfinished and newly updated manga.
A visible and stable manual update button, perhaps having it auto-update on browser startup.

As for actual issues there is, as already mentioned, compact mode being entirely broken on an 800p os x screen. 
The "Infinite scrolling" option is also pointless. It makes no difference on batoto, and disabling it on the other sites I have tested does not allow you to change page.

**Comment by Saishy** [comment]
At the phone right now, but about the sync between computers, I would need some way to get funding since maintaining a server is not free. And I see no way of doing that.

**Comment by ghost** [comment]
Understandable, I was under the impression that mozilla accounts offered something like that. The exporting feature I believe you mentioned before would also work. I'll update my comment with some more suggestions and issues.

**Comment by Saishy** [comment]
![Layout Image](http://i.imgur.com/JsWKi9Z.png)

Working on it :3

---

About the infinite scrolling thing, it is working. Disabling it allows you to view page-per-page by clicking at the far left/right of the page.
And about a button to go to the next chapter, there was a philosophical debate about what are bookmarks and manga reading and I decided to keep it the way it is.
The rest is already on the work.

**Comment by ghost** [comment]
Nice work, that looks great! I checked the infinite scrolling again, and it seems I just didn't notice how to change pages. However, disabling it still does nothing on Batoto. I tested on both Os X El Capitan and Windows 10.

Out of curiosity, how much would sync-servers cost? 
You could perhaps add a donation link in the settings?

**Comment by Saishy** [comment]
New 2.2.0 beta version on air!

About the sync-servers, something around 10 dollars per month.
If we go around the 1% client marketing rule, and those donate 1 dollar, we could get 8 dollar.
But I don't think those would be monthly...

It's a tricky situation.

**Comment by ghost** [comment]
I installed the beta. Import/export works perfectly, the update button responds(can't say more than that as there are no new chapters) and compact mode is compact.
However, infinite scrolling is now disabled even when it is marked, and the plugin does not show up in any way I can see on Batoto.

The only moral(i.e. not injecting ads) way to keep up the payments I can think of would be Patreon. Seems to be used mostly by artists, but that's not a rule.

Edit: Also, thanks!
Edit 2: Are we spamming rjbs91's email?

**Comment by Saishy** [comment]
Sorry about the bugs, I did fix and upload a new version right after but I guess you got it before it was up.
Well, anyway beta2 is up!

About the Patreon, I will create one since I'm starting a game dev company so I guess I will link there for the extension too.

Edit 2 Answer: Absolutely!

**Comment by Saishy** [comment]
https://addons.mozilla.org/pt-BR/firefox/addon/a-certain-manga-reader/contribute/installed/

Ta-da!

And I will be closing this issue since it got out of hand and most suggestions have been implemented.

But please feel free to create another one if you want to.

**Comment by ghost** [comment]
Many thanks, I will put up a list of any bugs I may find as well as all un-added suggestions from this thread.
