### ISSUE TITLE
Slowing down browser.

### ISSUE THREAD

**Issue by ghost** [Saishy/certainmangareader#9]
The add-on occasionally slows down the browser to a crawl. It becomes very slow to register anything, and uses a long time to complete any actions. When I eventually managed to disable the add-on the browser immediately went back to normal. This does not seem to coincide with chapter updates.
While the browser does use unusually much CPU and RAM when this happens, its still only about 30%.
Seems to happen on both OS X and Windows. Most often when opening the browser from OS X.

**Comment by Saishy** [comment]
Woa, that is indeed strange. Can you attach your export here for testing?
Is that frequently? Is there a way to trigger it?

**Comment by PeFoHe** [comment]
I am unable to recreate the problem on windows, so I suppose that might have been something else. On OS X El Capitan, however, it happens every time the browser is started or the plugin is enabled. It is a weak old laptop with a long manga list, but it worked fine on the previous versions. I'll check the processor and RAM use more carefully and attach the export when I get it started. It seems that I did not mention this in the OP, but while this slows the browser down to the point of uselessness, it goes back to normal after a few minutes.

**Comment by ghost** [comment]
I am unable to recreate the problem on windows, so I suppose that might have been something else.
 On OS X El Capitan, however, it happens every time the browser is started or the plugin is enabled.
 It is a weak old laptop with a long manga list, but it worked fine on the previous versions.

I just checked a bit more carefully. The CPU and RAM use is in fact well within the laptop's specs. Everything but firefox runs smoothly when it happens.
This only seems to happen when the plugin starts, and renders the browser useless for about 5 minutes. Opening a new window does not work, and restarting the browser restarts the problem.
This does not happen with an empty manga list.
Is it possible that the browser is not allowed to use the full power of the PC?

[Export.](https://github.com/Saishy/certainmangareader/files/129645/Export.txt)

**Comment by ghost** [comment]
A little update: this does happen on my far more powerful windows computer as well. 
On windows the problem is not triggered by enabling the plugin, so I can't recreate it.
Whether it's because of the OS or hardware the lag is far smaller on my windows desktop, and can be fixed by restarting the plugin.

**Comment by Saishy** [comment]
Some questions, are you using the compact mode?
Have you changed between the compact mode and normal mode?

**Comment by ghost** [comment]
I am using the compact mode, which I was not using before this update. I'll test in normal mode and edit with results.

**Comment by ghost** [comment]
The problem only exists in compact mode.

**Comment by ghost** [comment]
Moved to the general thread.
